# 홈과 택소노미에 노출할 섹션
mainSections = ["post"]

# RSS에 본문 전체 포함
rssFullContent = true

[author]
    name  = "Chaewon Kong"
    email = "chaewonkong@gmail.com"

# 푸터/소개 링크
[social]
    github   = "https://github.com/chaewonkong"
    linkedin = "https://www.linkedin.com/in/chaewonkong"
    twitter  = "https://x.com/alea_iacta_ist"
