# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
markdown: redcarpet
highlighter: rouge
# kramdown:
#   input: GFM

permalink: posts/:title:output_ext
# permalink: pretty
# relative_permalinks: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Setup
title: Leon
tagline: "Chaewon Kong's dev blog"
description: "Chaewon Kong's Dev Blog on web development and computer science. Frequently writes on JavaScript, React, React Native and Node."
url: http://lanyon.getpoole.com
baseurl: ""
paginate: 1

# About/contact
author:
  name: Chaewon Kong
  url: https://github.com/chaewonkong
  email: chaewonkong@gmail.com

# Custom vars
version: 1.0.0
