#!/usr/bin/env bash
#
# Catppuccin(Latte/Mocha) Chroma 스타일시트를 생성한다.
#
# 다크모드는 OS 설정과 수동 토글 두 경로로 적용되므로(spec.md §4.2), 다크 규칙을
# 두 스코프로 복제해야 한다. @media만 쓰면 OS가 라이트일 때 수동 다크 선택이
# 코드블록에 먹지 않는다.
#
# 생성물(assets/css/chroma.css)은 커밋한다. 빌드 시에는 이 스크립트를 돌리지 않는다.
#
# 사용법: ./scripts/gen-chroma.sh
set -euo pipefail
cd "$(dirname "$0")/.."

LIGHT_STYLE="catppuccin-latte"
DARK_STYLE="catppuccin-mocha"
OUT="assets/css/chroma.css"

# 헤더 주석과 규칙 앞 라벨 주석을 떼어내 셀렉터로 시작하는 줄만 남긴다
strip_rules() {
  grep -v '^/\* Generated using' | sed 's|^/\*[^*]*\*/ ||' | grep -v '^[[:space:]]*$'
}

{
  echo "/* generated by scripts/gen-chroma.sh — do not edit by hand */"
  echo
  echo "/* light: ${LIGHT_STYLE} */"
  hugo gen chromastyles --style="${LIGHT_STYLE}" | strip_rules
  echo
  echo "/* dark: ${DARK_STYLE} — OS 설정 추종 (수동 light 선택이 이긴다) */"
  echo "@media (prefers-color-scheme: dark) {"
  hugo gen chromastyles --style="${DARK_STYLE}" | strip_rules \
    | sed 's|^|  html:not([data-theme="light"]) |'
  echo "}"
  echo
  echo "/* dark: ${DARK_STYLE} — 수동 선택 (OS light를 이긴다) */"
  hugo gen chromastyles --style="${DARK_STYLE}" | strip_rules \
    | sed 's|^|html[data-theme="dark"] |'
} > "${OUT}"

echo "wrote ${OUT} ($(wc -l < "${OUT}" | tr -d ' ') lines)"
